CLS


PRINT "********************************************"
PRINT "*****************Hot dog stand**************"
PRINT "********************************************"
PRINT
PRINT
PRINT "You are now getting to run your own hot dog stand when ready press enter"
PRINT
INPUT spa
PRINT
PRINT "Now name your buisness"
PRINT
INPUT nam
PRINT
PRINT
PRINT "You are going to make your grand opening at a Baseball stadium you have $500 how many hot dogs do you want to buy if they are $1 a peice?"
PRINT
INPUT buy
PRINT
PRINT
PRINT "you are at the game how much are you going to sell the hot dogs for $1 $2 $3 or $4 a peice"
PRINT
PRINT
INPUT sell
PRINT
IF buy = " 501 " THEN profit = "became bankrupt"
PRINT "y: "; profit

